import {
  Identifier,
  LinkedEntity,
  Location,
  PeriodOfTime,
  DataProduct as IDataProduct,
} from 'generated/backofficeSchemas';

export class DataProduct {
  constructor(
    public uid?: string,
    public changeComment?: string,
    public changeTimestamp?: string,
    public contactPoint?: Array<LinkedEntity>,
    public description?: Array<string>,
    public distribution?: Array<LinkedEntity>,
    public identifier?: Array<Identifier>,
    public issued?: string,
    public keywords?: string,
    public modified?: string,
    public temporalExtent?: Array<PeriodOfTime>,
    public title?: Array<string>,
    public versionInfo?: string,
    public accessRight?: string,
    public accrualPeriodicity?: string,
    public category?: LinkedEntity[],
    public created?: string,
    public dctIdentifier?: string,
    public documentation?: string,
    public editorId?: string,
    public fileProvenance?: string,
    public hasPart?: Array<LinkedEntity>,
    public hasQualityAnnotation?: string,
    public instanceChangedId?: string,
    public instanceId?: string,
    public isPartOf?: Array<LinkedEntity>,
    public metaId?: string,
    public operation?: string,
    public provenance?: Array<string>,
    public publisher?: Array<LinkedEntity>,
    public qualityAssurance?: string,
    public relation?: Array<LinkedEntity>,
    public spatialExtent?: Array<Location>,
    public status?: IDataProduct['status'],
    public toBeDelete?: string,
    public type?: string,
    public version?: string,
  ) {}
}
