import { Identifier, LinkedEntity, DataProduct as DataProductType } from 'generated/backofficeSchemas';

export class DataProduct implements DataProductType {
  constructor(
    public accessRight?: string,
    public accrualPeriodicity?: string,
    public category?: LinkedEntity[],
    public changeComment?: string,
    public changeTimestamp?: string,
    public contactPoint?: Array<LinkedEntity>,
    public created?: string,
    public description?: Array<string>,
    public distribution?: Array<LinkedEntity>,
    public documentation?: string,
    public editorId?: string,
    public fileProvenance?: string,
    public hasPart?: Array<LinkedEntity>,
    public identifier?: Array<Identifier>,
    public instanceChangedId?: string,
    public instanceId?: string,
    public isPartOf?: Array<LinkedEntity>,
    public issued?: string,
    public keywords?: string,
    public metaId?: string,
    public modified?: string,
    public operation?: string,
    public provenance?: Array<string>,
    public publisher?: Array<LinkedEntity>,
    public qualityAssurance?: string,
    public relation?: Array<LinkedEntity>,
    public spatialExtent?: Array<LinkedEntity>,
    public status?: DataProductType['status'],
    public temporalExtent?: Array<LinkedEntity>,
    public title?: Array<string>,
    public toBeDelete?: string,
    public type?: string,
    public uid?: string,
    public version?: string,
    public versionInfo?: string,
  ) {}
}
