server {
    listen 80;
    root /usr/share/nginx/html/;
    server_name _;

    # Automatically replace the rewrite location below with root url path
    rewrite ^/(.*)$ /$1 last;
    location / {
        try_files $uri$args $uri$args/ /index.html;
    }

    # Proxy api requests on deployed version to backoffice API endpoint
    location /api {
      rewrite /api/(.*) /$1 break;
      proxy_pass https://ics-c.epos-ip.org/demo/k8s-epos-deploy/backoffice-test-env/api/v1
    }
}
