export enum Entity {
  CONTACT_POINT = 'ContactPoint',
  DATA_PRODUCT = 'DataProduct',
  DISTRIBUTION = 'Distribution',
  DOCUMENTATION = 'Documentation',
  GROUP = 'Group',
  IDENTIFIER = 'Identifier',
  LOCATION = 'Location',
  MAPPING = 'Mapping',
  OPERATION = 'Operation',
  ORGANIZATION = 'Organization',
  PERIOD_OF_TIME = 'PeriodOfTime',
  PERSON = 'Person',
  USER = 'User',
  WEBSERVICE = 'WebService',
  CATEGORY = 'Category',
}
